language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.0
- 2.1
- 2.2
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-execute.gemspec
- gem install sensu-plugins-execute-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: ljsnBqfzivtmMmNEvZ6185TpKJDprpkAUIwp6cX8WDE8ZUEJ8FMqpoihFsxFewQYkFYaBJM5kZeQXLvLY0G2xOGcFgJEQxrLnUUNrb3k34apEmz+39/tCTVTKXryMoJkGytUch3KDcjryn9ACFIrCp3kAz7FqAtlsd4W6jWE+g4=
  gem: sensu-plugins-execute
  on:
    tags: true
    all_branches: true
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-execute
